#include "common/includes.h"

#ifndef _S_ATOMS_H_
#define _S_ATOMS_H_

#define MR_FLAG_X (0x00000050)
#define MR_FLAG_Y (0x00000060)
#define MR_FLAG_W (0x00000070)
#define MR_FLAG_H (0x00000080)

Atom XA_WM_STATE;
Atom XA_WM_PROTOCOLS;
Atom XA_WM_DELETE_WINDOW;
Atom EA_NET_WM_NAME;
Atom EA_NET_WM_ICON_NAME;
Atom EA_NET_WM_WINDOW_TYPE;
Atom EA_NET_WM_WINDOW_TYPE_DESKTOP;
Atom EA_NET_WM_WINDOW_TYPE_DIALOG;
Atom EA_NET_WM_WINDOW_TYPE_NORMAL;
Atom EA_NET_WM_STATE;
Atom EA_NET_WM_STATE_MODAL;
Atom EA_NET_WM_STATE_MAXIMIZED_VERT;
Atom EA_NET_WM_STATE_MAXIMIZED_HORZ;
Atom EA_NET_WM_STATE_HIDDEN;
Atom EA_NET_WM_STATE_FOCUSED;
Atom EA_NET_ALLOWED_ACTIONS;
Atom EA_NET_WM_ACTION_MOVE;
Atom EA_NET_WM_ACTION_RESIZE;
Atom EA_NET_WM_ACTION_MINIMIZE;
Atom EA_NET_WM_ACTION_MAXIMIZE_VERT;
Atom EA_NET_WM_ACTION_MAXIMIZE_HORZ;
Atom EA_NET_WM_ACTION_CLOSE;
Atom EA_NET_SUPPORTED;
Atom EA_NET_CLIENT_LIST;
Atom EA_NET_CLIENT_LIST_STACKING;
Atom EA_NET_NUMBER_OF_DESKTOPS;
Atom EA_NET_DESKTOP_GEOMETRY;
Atom EA_NET_DESKTOP_VIEWPORT;
Atom EA_NET_CURRENT_DESKTOP;
Atom EA_NET_ACTIVE_WINDOW;
Atom EA_NET_WORKAREA;
Atom EA_NET_SUPPORTING_WM_CHECK;
Atom EA_NET_CLOSE_WINDOW;
Atom EA_NET_MOVERESIZE_WINDOW;
Atom EA_NET_WM_MOVERESIZE;

void atoms_init( Display *conn );

#endif
